### PR TITLE
Feat/1/help cmd line

### PR DESCRIPTION
**Pull request by embmk**
Finally the changes could be committed to the server. Now it's time to decide if it's worth pulling them into the master.

The dummy skeleton doesn't exist anymore. Now there is a Eclipse CDT Project in a subfolder called "code". The folder also contains separate folder for source and header files and are called "src" and "inc".

### CODE REVIEW

**Comment by codders** [comment]
- This  PR breaks the build.
- There are additional build dependencies (libboost-dev, libboost-program-options, cmake) that should be documented
- There doesn't seem to be a libboost-program-options package in Debian without a named version (e.g. 1.62.0) - which package do I need to install?
- You appear to have checked a number of derived resources into version control (log files, bin files, your shelldump.txt). Please only commit source files.

Please resolve these issues before we can merge the code.

**Comment by codders** [comment]
Additionally:
 - For future merge requests, please do not use CamelCase in branch names - hyphens are preferred.
 - Code contains commented but non-functional lines of code. Please remove them for the final PR
 - Indentation is inconsistent. Please pick an indentation style and stick to it.

**Comment by embmk** [comment]
I added the packages and corresponding versions that are installed on my system to the readme-file.

**Comment by codders** [comment]
Hi Moritz,

 - Please update the include directory (CMakeLists.txt:23)
 - Please rebase and squash unnecessary commits (https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) so that we only have one or two meaningful commits here
 - Please update the README to reference libboost-program-options-dev as a required package (instead of libboost-program-options1.58.0)

When you're done, please assign me the pull request for review.

Thanks!

**Comment by codders** [comment]
This pull request is a thing of beauty - excellent work. Thanks very much.

**Pull request merged**
