### PR TITLE
Use patches, to see our changes on common-api-dbus library

### PR DESCRIPTION
**Pull request by patriotyk**
This pull request fixses #83, also all changes to dbus librarry moved to patch.

### CODE REVIEW

**Comment by cajun-rat** [comment]
This looks good: clearly separating out the changes we are making to the libraries is a good thing.

We/I need to figure out how this will work when being built in GDP. The ideal case would be to get these changes upstreamed to GDP, but if we can't do that then we'll have to rethink how the Yocto build will work. The current plan for the Yocto recipe is to build against the GDP-provided platform builds of these libraries.

**Comment by patriotyk** [comment]
Sorry, what is GDP?

**Comment by taheris** [comment]
[GENIVI Development Platform](https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=11567210).

**Comment by cajun-rat** [comment]
GDP stands for Genivi Development Platform, it is a Yocto/OpenEmbedded/Poky based embedded Linux distribution for cars. It operates differently to desktop Linux distributions like Debian because the entire system is built from source. This means that it is possible to apply patches to 'global' system libraries like dbus when building software in GDP.

When we get sota_client_cpp building in GDP we will want to use these patched 'global' libraries rather than the locally built versions we have to use for Debian-like desktop Linux. This is because patching dbus is quite simple in GDP compared to patching the Debian (or Red Hat) dbus library.

**Pull request merged**
