### PR TITLE
Added top-level Makefile

### PR DESCRIPTION
**Pull request by codders**
Added a top-level Makefile to simplify buliding, cleaning and CI setup.

### CODE REVIEW

**Comment by embmk** [comment]
Now the executable is placed in a folder named "out", but in the meantime you introduced a folder named "target" for the executable.

**Comment by codders** [comment]
I reverted that change and removed all references to the 'target' folder. If you make clean and make you should see the binary ends up in 'out'. Is that not your experience?

**Comment by embmk** [comment]
Yes, I am used to have a folder "out" for the executable. I was just wondering, and after excessive rebasing and squashing on my side yesterday I just wanted to play safe on this change. I have a local master merged and ready to push for finishing this pull request.

**Comment by codders** [comment]
If you make your pull request, we can merge that first. I will resolve any conflicts with my pull request after that.

**Comment by codders** [comment]
(I personally prefer to have the binaries in the 'target' folder, but I didn't want to mess with your pull request).

**Comment by embmk** [comment]
Oh, then I messed something up when rebasing because I initiallly intended to stick to your convention.

**Comment by codders** [comment]
k. Repushed now with 'target' as the output directory.

**Comment by codders** [comment]
But anyway let's get your changes in first - easier for me to fix my pull request as it's quite small.

**Comment by embmk** [comment]
I trying to get the pull request done, but now I discovered that all commits pup up three times in the log. I think I have to start again with a mint clone. Unless it's OK if I use the button here on the Webpage. But I expect of course that it is at least recommended to do the command line procedure...

**Comment by embmk** [comment]
OK one last question, in the masters log I see a commit "Merge pull request #...". Is this set automatically or do I have to write the commit description using the #pull-request myself?

**Comment by codders** [comment]
The merge-commits are created by github when you accept a merge request (by clicking the 'Merge pull request' button on github. You shouldn't be merging or generating merge commits on your local machine. You should only be rebasing local branches.

**Pull request merged**
