### PR TITLE
Feat/2/logging framework

### PR DESCRIPTION
**Pull request by embmk**

### CODE REVIEW

**Comment by embmk** [comment]
There is something missing here, I have to get git to push it..

**Comment by embmk** [comment]
I forgot to make a forced push. I squashed some of my commits but didn't dare to touch yours.

**Comment by codders** [comment]
The branch still has conflicts with master and cannot be merged. I don't mind if you change or squash my commits, but obviously the Travis changes should be preserved.

Given that the branch is a bit of a mess, I would recommend creating a new branch from the current master, and cherry-picking the changes you need from here across to that branch. But I don't really have any strong feelings about it.

Let me know if you need me to get the branch to a state that can be merged. (Obviously my preference here would be that you do it).

**Comment by codders** [comment]
Looks good - thanks!

**Pull request merged**
