### PR TITLE
Dbusgateway implementation

### PR DESCRIPTION
**Pull request by patriotyk**
I have not covered events, because without mocks it is not possible, and I didn't have time to integrate gtests #48

### CODE REVIEW

**Comment by taheris** [comment]
@patriotyk: would it be possible to remove the generated code from source control?
(@cajun-rat: unless you have a different opinion?)

**Comment by cajun-rat** [comment]
Avoiding checking in generated code would be nice, but I'd like to understand the trade-off first:  Is generating these files at build time easy?  What tools are required?

If it turns out to be a pain (e.g. requires Java), could you put a note in the commit message that details how these files were generated (command line and the versions of the tools used), please?

**Comment by patriotyk** [comment]
I don't think it will be easy to autogenerate code at build time because codegenerators requires java and maven to build it. Also GENIVI provides builded codegenerators, but they are architecture dependant. This librarry is designed to work with codegenerators only, and there is no any documentation how to use it without codegenerators

**Comment by cajun-rat** [comment]
Agreed. 'maven' is a pretty good reason to check in the generated code.

Could you update the commit message with the commands used to generate the files, please?  Then it is good to merge.

**Comment by patriotyk** [comment]
Ok, and I will add also fixed .fidl file.

**Comment by cajun-rat** [comment]
Sorry, I've just spotted an issue that I missed the first time. When building with -DBUILD_WITH_DBUS_GATEWAY=ON, there are several checked in files that are modified as part of the build. These appear to be generated as part of the build process, and so shouldn't be checked in.

To Reproduce:
```
git clone into /tmp/foo
cd /tmp/foo
mkdir build
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_DBUS_GATEWAY=ON ..
make
git status # Produces lots of output
```

The files that appear as modified should probably be removed from source control with 'git rm', and the 'Untracked' files should be .gitignore'd

It is a bit annoying that the autotools build process generates files in the source directory: it is possible to build those third_party libraries with cmake?

**Comment by patriotyk** [comment]
I have changed libdbus to build with cmake but I still need to run ./autogen.sh to generate package-config file, because commonapi-dbus use it.

**Comment by cajun-rat** [comment]
I'm having trouble building this on my desktop machine, but since it works on CI I will merge it anyway to unblock future work and I'll investigate a fix.

**Pull request merged**
